# -*- coding: utf-8 -*-
"""Afficionado_Coffee_Roasters.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FWNDYlXvt7fEga0wXFCsVUndEuyCXbNt

---
**Afficionado Coffee Roasters**


---


Import File
"""

from google.colab import files

uploaded = files.upload()

"""Import Libraries"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""Load Data"""

df = pd.read_csv("Afficionado Coffee Roasters.xlsx.csv")

"""Check Data"""

df.head(),  df.shape, df.info(), df.columns

"""

---

**Data Cleaning**


---


Missing Values"""

df.isnull().sum()

df["product_id"].isnull().sum()

"""Duplicate Records"""

df.duplicated().sum()

df = df.drop_duplicates()

df.groupby("product_id")["product_detail"].nunique().sort_values(ascending=False)

"""Validate Quantities"""

df[df["transaction_qty"] <= 0]

df = df[df["transaction_qty"] > 0]

df["transaction_qty"].describe()

plt.figure(figsize=(8,5))
sns.histplot(df["transaction_qty"], bins=8, kde=True)
plt.title("Distribution of Transaction Quantity")
plt.xlabel("Transaction Quantity")
plt.ylabel("Frequency")
plt.show()

"""Validate Unit Price"""

df[df["unit_price"] <= 0]

df = df[df["unit_price"] > 0]

df["unit_price"].describe()

plt.figure(figsize=(8,5))
sns.histplot(df["unit_price"], bins=30, kde=True)
plt.title("Distribution of Unit Price")
plt.xlabel("Unit Price")
plt.ylabel("Frequency")
plt.show()

"""Create Revenue"""

df["revenue"] = (df["transaction_qty"] * df["unit_price"])

df[["transaction_qty","unit_price","revenue"]].head()

"""Exporting Cleaned Data"""

df.to_csv("cleaned_data.csv",index=False)

files.download("cleaned_data.csv")

"""

---
**Revenue Computation**


---


Revenue by Product"""

product_revenue = (
    df.groupby("product_detail")
      .agg(
          total_revenue=("revenue","sum")
      )
      .reset_index()
)

product_revenue.head()

"""Revenue by Product Type"""

type_revenue = (
    df.groupby("product_type")
      .agg(
          total_revenue=("revenue","sum")
      )
      .reset_index()
)

type_revenue

top15 = type_revenue.sort_values(
    "total_revenue",
    ascending=False
).head(15)

plt.figure(figsize=(12,7))
sns.barplot(
    data=top15,
    x="total_revenue",
    y="product_type"
)

plt.title("Top 15 Product Types by Revenue")
plt.xlabel("Revenue")
plt.ylabel("Product Type")
plt.show()

"""Revenue by Category"""

category_revenue = (
    df.groupby("product_category")
      .agg(
          total_revenue=("revenue","sum")
      )
      .reset_index()
)

category_revenue

category_revenue_df = category_revenue.reset_index()
category_revenue_df = category_revenue_df.rename(columns={'revenue': 'total_revenue'})

plt.figure(figsize=(10,6))
sns.barplot(
    data=category_revenue_df.sort_values("total_revenue", ascending=False),
    x="total_revenue",
    y="product_category"
)

plt.title("Revenue by Product Category")
plt.xlabel("Revenue")
plt.ylabel("Category")
plt.show()

"""

---

**Product Popularity Analysis**


---
Total Units Sold Per Product
"""

product_volume = (
    df.groupby("product_detail")
      .agg(
          units_sold=("transaction_qty","sum")
      )
      .reset_index()
)

product_volume.head()

"""Ranking Products"""

product_volume["volume_rank"] = (
    product_volume["units_sold"]
    .rank(
        ascending=False,
        method="dense"
    )
)

"""Top 10 Products"""

top10_volume = (
    product_volume
    .sort_values(
        "units_sold",
        ascending=False
    )
    .head(10)
)

top10_volume

plt.figure(figsize=(12,6))
sns.barplot(
    data=top10_volume,
    x="units_sold",
    y="product_detail"
)

plt.title("Top 10 Products by Units Sold")
plt.xlabel("Units Sold")
plt.ylabel("Product")
plt.show()

"""Bottom 10 Products"""

bottom10_volume = (
    product_volume
    .sort_values(
        "units_sold",
        ascending=True
    )
    .head(10)
)

bottom10_volume

plt.figure(figsize=(12,6))
sns.barplot(
    data=bottom10_volume,
    x="units_sold",
    y="product_detail"
)

plt.title("Bottom 10 Products by Units Sold")
plt.xlabel("Units Sold")
plt.ylabel("Product")
plt.show()

"""

---

**Revenue Contribution Analysis**


---

Revenue Per Product"""

revenue_per_product = df['transaction_qty'].sum()/df['unit_price'].sum()
revenue_per_product

"""Revenue Share %"""

total_revenue = df["revenue"].sum()

product_revenue["revenue_share_pct"] = (
    product_revenue["total_revenue"]
    / total_revenue
) * 100
total_revenue

"""Revenue Ranking"""

product_revenue["revenue_rank"] = (
    product_revenue["total_revenue"]
    .rank(
        ascending=False,
        method="dense"
    )
)
product_revenue.head()

"""Compare Volume Rank vs Revenue Rank"""

comparison = (
    product_volume.merge(
        product_revenue,
        on="product_detail"
    )
)

comparison.head()

plt.figure(figsize=(8,6))

sns.scatterplot(
    data=comparison,
    x="volume_rank",
    y="revenue_rank"
)

plt.title("Revenue Rank vs Volume Rank")
plt.xlabel("Volume Rank")
plt.ylabel("Revenue Rank")
plt.show()

"""Rank Gap"""

comparison["rank_gap"] = (
    comparison["volume_rank"]
    -
    comparison["revenue_rank"]
)
comparison["rank_gap"].head()

plt.figure(figsize=(10,6))

sns.histplot(
    comparison["rank_gap"],
    bins=20,
    kde=True
)

plt.title("Distribution of Rank Gap")
plt.xlabel("Rank Gap")
plt.ylabel("Count")
plt.show()

"""

---

**Category & Product-Type Performance**


---
Revenue Share by Category
"""

category_revenue["category_share_pct"] = (
    category_revenue["total_revenue"]
    /
    category_revenue["total_revenue"].sum()
) * 100
category_revenue["category_share_pct"]

plt.figure(figsize=(8,8))

plt.pie(
    category_revenue_df["total_revenue"],
    labels=category_revenue_df["product_category"],
    autopct="%1.1f%%",
    startangle=90
)

plt.title("Revenue Share by Category")
plt.show()

"""Product-Type Contribution"""

type_revenue["type_share_pct"] = (
    type_revenue["total_revenue"]
    /
    type_revenue["total_revenue"].sum()
) * 100
type_revenue["type_share_pct"]

top10 = type_revenue.sort_values(
    "type_share_pct",
    ascending=False
).head(10)

plt.figure(figsize=(10,6))

sns.barplot(
    data=top10,
    x="type_share_pct",
    y="product_type"
)

plt.title("Top Product Types by Revenue Share")
plt.xlabel("Revenue Share (%)")
plt.ylabel("Product Type")
plt.show()

"""Core Category Dependence"""

category_revenue.sort_values(
    "total_revenue",
    ascending=False
)
category_revenue

"""---
**Revenue Concentration & Menu Balance**

---


Sort Products

"""

pareto = (
    product_revenue
    .sort_values(
        "total_revenue",
        ascending=False
    )
    .reset_index(drop=True)
)
pareto

"""Cumulative Revenue %"""

pareto["cumulative_pct"] = (
    pareto["total_revenue"]
    .cumsum()
    /
    pareto["total_revenue"].sum()
) * 100
pareto

fig, ax1 = plt.subplots(figsize=(14,6))

sns.barplot(
    data=pareto,
    x="product_detail",
    y="total_revenue",
    color="skyblue",
    ax=ax1
)

ax1.tick_params(axis='x', rotation=90)
ax1.set_ylabel("Revenue")

ax2 = ax1.twinx()

ax2.plot(
    pareto.index,
    pareto["cumulative_pct"],
    color="red",
    marker="o"
)

ax2.set_ylabel("Cumulative %")
ax2.axhline(80, color="green", linestyle="--")

plt.title("Pareto Analysis of Product Revenue")
plt.show()

"""Pareto Classification"""

pareto["category"] = np.where(
    pareto["cumulative_pct"] <= 80,
    "Revenue Anchor",
    "Long Tail"
)
pareto

"""Revenue Anchors"""

anchors = (
    pareto[
        pareto["category"]
        == "Revenue Anchor"
    ]
)
anchors.head()



"""Long Tail Products"""

long_tail = (
    pareto[
        pareto["category"]
        == "Long Tail"
    ]
)
long_tail.head()

plt.figure(figsize=(6,6))

sns.countplot(
    data=pareto,
    x="category"
)

plt.title("Revenue Anchor vs Long Tail Products")
plt.xlabel("Category")
plt.ylabel("Number of Products")
plt.show()

"""Diversification Risk"""

len(anchors)

len(long_tail)

"""---
**KPI Creation**


---
Product Revenue Contribution %


"""

total_revenue = df["revenue"].sum()
product_revenue = (df.groupby("product_detail")["revenue"].sum())

highest_contribution = (product_revenue.max() / total_revenue) * 100

print(round(highest_contribution, 2))

"""Product Sales Volume"""

total_units = df["transaction_qty"].sum()

print(total_units)

"""Category Revenue Share"""

category_revenue = (
    df.groupby("product_category")["revenue"]
      .sum()
)

highest_category_share = (
    category_revenue.max() /
    category_revenue.sum()
) * 100

print(round(highest_category_share,2))

"""Revenue Concentration Ratio"""

top_products = pareto[pareto["cumulative_pct"] <= 80]

ratio = (
    top_products["total_revenue"].sum()
    /
    total_revenue
) * 100

print(round(ratio,2))

"""Product Efficiency Score"""

efficiency = (
    df["revenue"].sum()
    /
    df["transaction_qty"].sum()
)

print(round(efficiency,2))

store_revenue = (
    df.groupby("store_location")
      .agg(total_revenue=("revenue","sum"))
      .reset_index()
)

plt.figure(figsize=(8,5))

sns.barplot(
    data=store_revenue,
    x="store_location",
    y="total_revenue"
)

plt.title("Revenue by Store Location")
plt.xlabel("Store Location")
plt.ylabel("Revenue")
plt.xticks(rotation=15)
plt.show()

"""**COMPLETE**"""